### ISSUE TITLE
clean test data

### ISSUE THREAD

**Issue by tillmo** [tillmo/erpnext-client#20]
using manual inspection, ensure that all json1 fields contain the information that can be extracted from the PDF.  

And automatically check whether they match the schema, see [https://towardsdatascience.com/how-to-use-json-schema-to-validate-json-documents-ae9d8d1db344](https://www.freelancer.com/users/l.php?url=https:%2F%2Ftowardsdatascience.com%2Fhow-to-use-json-schema-to-validate-json-documents-ae9d8d1db344&sig=374955c1a5c09cae5686b168dd313626d1ce66a27965971431c6771667973fd1)
Validation should only check and not modify the json1 values.
If there is a validation error, either the json1 value or the schema needs to be corrected. It should be carefully decided which one to correct.

**Comment by Andrewed95** [comment]
1. All json1 fields were updated 
2. Validation was added based on the schema. There was no validation error.

**Comment by Andrewed95** [comment]
https://github.com/tillmo/erpnext-client/pull/19/commits/deea50368da4cca0c4c5c7d737a65dee6312a0d6

**Comment by Andrewed95** [comment]
Done
