### ISSUE TITLE
use data model from #18 as intermediate data structure

### ISSUE THREAD

**Issue by tillmo** [tillmo/erpnext-client#22]
split of the code in `purchase_invoice.py`, function `parse_invoice_json` into two functions:
1. the value in the json field is used to create data according to the data model in #18 is an intermediate data structure
2.  from this, an ERPNext invoice is generated.
The purpose is that the first function can be used to test the invoice AI, by comparing the result with the value of the json1 field.

**Comment by Andrewed95** [comment]
Done
